"""empty message

Revision ID: b5093a6d4142
Revises: 
Create Date: 2022-06-03 06:06:16.953243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5093a6d4142'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('show',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('artist_name', sa.String(), nullable=True),
    sa.Column('venue_name', sa.String(), nullable=True),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('venue', sa.Column('show_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'venue', 'show', ['show_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venue', type_='foreignkey')
    op.drop_column('venue', 'show_id')
    op.drop_table('show')
    # ### end Alembic commands ###
